git:
  depth: false
  submodules: false
branches:
  only:
    - master
language: ruby
rvm:
  - 2.3.3
env:
  global:
    - CC_TEST_REPORTER_ID=77034bfbc39e1717ca44c847f109033b7635c55fb3996f09f2da6fc4341a25ee
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
